---
include:
 - board: seeeduino_xiao_ble
   shield: roBa_R
   snippet: zmk-usb-logging
   cmake-args: -DCONFIG_ZMK_STUDIO=n -DCONFIG_LOG_BUFFER_SIZE=16384 -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000
   artifact-name: roBa_R-usb-logging
